const selection = document.getElementById("language");

const languageDict = {
    secretText: {
        DE: "Kennwort eingeben",
        EN: "Enter password",
        NL: "Wachtwoord invoeren",
        HR: "Unesite lozinku",
        ES: "Introducir contraseña",
        IT: "Inserisci password",
        FR: "Entrez le mot de passe",
        PL: "Wprowadź hasło",
        HU: "Adja meg a jelszót",
        SK: "Zadajte heslo",
        CZ: "Zadejte heslo",
    },
    cancelSecretBtn: {
        DE: "Abbrechen",
        EN: "Cancel",
        NL: "Annuleren",
        HR: "Odustani",
        ES: "Cancelar",
        IT: "Annulla",
        FR: "Annuler",
        PL: "Anuluj",
        HU: "Mégse",
        SK: "Zrušiť",
        CZ: "Zrušit",
    },
    chooseFolderTxt: {
        DE: "Es muss ein Ordner zum Speichern der Datei ausgewählt werden!",
        EN: "A folder must be selected to save the file!",
        NL: "Er moet een map worden geselecteerd om het bestand op te slaan!",
        HR: "Morate odabrati mapu za spremanje datoteke!",
        ES: "¡Debe seleccionar una carpeta para guardar el archivo!",
        IT: "È necessario selezionare una cartella per salvare il file!",
        FR: "Un dossier doit être sélectionné pour enregistrer le fichier !",
        PL: "Należy wybrać folder do zapisania pliku!",
        HU: "Mappát kell kiválasztani a fájl mentéséhez!",
        SK: "Je potrebné vybrať priečinok na uloženie súboru!",
        CZ: "Musíte vybrat složku pro uložení souboru!",
    },
    chooseFolder: {
        DE: "Ordner auswählen",
        EN: "Choose Folder",
        NL: "Map kiezen",
        HR: "Odaberi mapu",
        ES: "Seleccionar carpeta",
        IT: "Scegli cartella",
        FR: "Choisir un dossier",
        PL: "Wybierz folder",
        HU: "Mappa kiválasztása",
        SK: "Vybrať priečinok",
        CZ: "Vybrat složku",
    },
    roomNumberLabel: {
        DE: "Zimmernummer",
        EN: "Room Number",
        NL: "Kamernummer",
        HR: "Broj sobe",
        ES: "Número de habitación",
        IT: "Numero della stanza",
        FR: "Numéro de chambre",
        PL: "Numer pokoju",
        HU: "Szobaszám",
        SK: "Číslo izby",
        CZ: "Číslo pokoje",
    },
    quantityLabel: {
        DE: "Personen",
        EN: "Guests",
        NL: "Personen",
        HR: "Osobe",
        ES: "Personas",
        IT: "Persone",
        FR: "Personnes",
        PL: "Osoby",
        HU: "Vendégek",
        SK: "Osoby",
        CZ: "Osoby",
    },
    startCheckInBtn: {
        DE: "Check-In Starten",
        EN: "Start Check-In",
        NL: "Check-in Starten",
        HR: "Započni prijavu",
        ES: "Iniciar check-in",
        IT: "Avvia check-in",
        FR: "Commencer l'enregistrement",
        PL: "Rozpocznij zameldowanie",
        HU: "Bejelentkezés indítása",
        SK: "Spustiť check-in",
        CZ: "Zahájit check-in",
    },
    cancelCheckInBtn: {
        DE: "Check-In Abbrechen",
        EN: "Cancel Check-In",
        NL: "Check-in Annuleren",
        HR: "Otkaži prijavu",
        ES: "Cancelar check-in",
        IT: "Annulla check-in",
        FR: "Annuler l'enregistrement",
        PL: "Anuluj zameldowanie",
        HU: "Bejelentkezés megszakítása",
        SK: "Zrušiť check-in",
        CZ: "Zrušit check-in",
    },
    nameLabel: {
        DE: "Vor- und Nachname",
        EN: "First and Last Name",
        NL: "Voor- en achternaam",
        HR: "Ime i prezime",
        ES: "Nombre y apellido",
        IT: "Nome e cognome",
        FR: "Prénom et nom",
        PL: "Imię i nazwisko",
        HU: "Vezetéknév és keresztnév",
        SK: "Meno a priezvisko",
        CZ: "Jméno a příjmení",
    },
    contactLabel: {
        DE: "E-Mail/Telefon",
        EN: "Email/Phone",
        NL: "E-mail/Telefoon",
        HR: "E-mail/Telefon",
        ES: "Correo electrónico/Teléfono",
        IT: "E-mail/Telefono",
        FR: "E-mail/Téléphone",
        PL: "E-mail/Telefon",
        HU: "E-mail/Telefon",
        SK: "E-mail/Telefón",
        CZ: "E-mail/Telefon",
    },
    tableContact: {
        DE: "Kontakt",
        EN: "Contact",
        NL: "Contact",
        HR: "Kontakt",
        ES: "Contacto",
        IT: "Contatto",
        FR: "Contact",
        PL: "Kontakt",
        HU: "Kapcsolat",
        SK: "Kontakt",
        CZ: "Kontakt",
    },
    birthdateLabel: {
        DE: "Geburtstag",
        EN: "Birthdate",
        NL: "Geboortedatum",
        HR: "Datum rođenja",
        ES: "Fecha de nacimiento",
        IT: "Data di nascita",
        FR: "Date de naissance",
        PL: "Data urodzenia",
        HU: "Születési dátum",
        SK: "Dátum narodenia",
        CZ: "Datum narození",
    },
    // tableBirthdate: {
    //     DE: "Geburtstag",
    //     EN: "Birthdate",
    //     NL: "Geboortedatum",
    //     HR: "Datum rođenja",
    //     ES: "Fecha de nacimiento",
    //     IT: "Data di nascita",
    //     FR: "Date de naissance",
    //     PL: "Data urodzenia",
    //     HU: "Születési dátum",
    //     SK: "Dátum narodenia",
    //     CZ: "Datum narození",
    // },
    countryLabel: {
        DE: "Land",
        EN: "Country",
        NL: "Land",
        HR: "Država",
        ES: "País",
        IT: "Paese",
        FR: "Pays",
        PL: "Kraj",
        HU: "Ország",
        SK: "Krajina",
        CZ: "Země",
    },
    cityLabel: {
        DE: "Ort",
        EN: "City",
        NL: "Stad",
        HR: "Grad",
        ES: "Ciudad",
        IT: "Città",
        FR: "Ville",
        PL: "Miasto",
        HU: "Város",
        SK: "Mesto",
        CZ: "Město",
    },
    zipcodeLabel: {
        DE: "PLZ",
        EN: "ZIP Code",
        NL: "Postcode",
        HR: "Poštanski broj",
        ES: "Código postal",
        IT: "CAP",
        FR: "Code postal",
        PL: "Kod pocztowy",
        HU: "Irányítószám",
        SK: "PSČ",
        CZ: "PSČ",
    },
    streetLabel: {
        DE: "Straße",
        EN: "Street",
        NL: "Straat",
        HR: "Ulica",
        ES: "Calle",
        IT: "Via",
        FR: "Rue",
        PL: "Ulica",
        HU: "Utca",
        SK: "Ulica",
        CZ: "Ulice",
    },
    copyAddressLabel: {
        DE: "Adresse für nächste Person kopieren",
        EN: "Copy address for next person",
        NL: "Adres kopiëren voor volgende persoon",
        HR: "Kopiraj adresu za sljedeću osobu",
        ES: "Copiar dirección para la siguiente persona",
        IT: "Copia indirizzo per la prossima persona",
        FR: "Copier l'adresse pour la personne suivante",
        PL: "Skopiuj adres dla następnej osoby",
        HU: "Cím másolása a következő személyhez",
        SK: "Skopírovať adresu pre ďalšiu osobu",
        CZ: "Kopírovat adresu pro další osobu",
    },
    nextBtn: {
        DE: "Weiter",
        EN: "Next",
        NL: "Volgende",
        HR: "Dalje",
        ES: "Siguiente",
        IT: "Avanti",
        FR: "Suivant",
        PL: "Dalej",
        HU: "Következő",
        SK: "Ďalej",
        CZ: "Další",
    },
    tableName: {
        DE: "Name",
        EN: "Name",
        NL: "Naam",
        HR: "Ime",
        ES: "Nombre",
        IT: "Nome",
        FR: "Nom",
        PL: "Nazwa",
        HU: "Név",
        SK: "Meno",
        CZ: "Jméno",
    },
    tableCountry: {
        DE: "Land",
        EN: "Country",
        NL: "Land",
        HR: "Država",
        ES: "País",
        IT: "Paese",
        FR: "Pays",
        PL: "Kraj",
        HU: "Ország",
        SK: "Krajina",
        CZ: "Země",
    },
    tableCity: {
        DE: "Ort",
        EN: "City",
        NL: "Stad",
        HR: "Grad",
        ES: "Ciudad",
        IT: "Città",
        FR: "Ville",
        PL: "Miasto",
        HU: "Város",
        SK: "Mesto",
        CZ: "Město",
    },
    tableZipcode: {
        DE: "PLZ",
        EN: "ZIP Code",
        NL: "Postcode",
        HR: "Poštanski broj",
        ES: "Código postal",
        IT: "CAP",
        FR: "Code postal",
        PL: "Kod pocztowy",
        HU: "Irányítószám",
        SK: "PSČ",
        CZ: "PSČ",
    },
    tableStreet: {
        DE: "Straße",
        EN: "Street",
        NL: "Straat",
        HR: "Ulica",
        ES: "Calle",
        IT: "Via",
        FR: "Rue",
        PL: "Ulica",
        HU: "Utca",
        SK: "Ulica",
        CZ: "Ulice",
    },
    tableNationality: {
        DE: "Nationalität",
        EN: "Nationality",
        NL: "Nationaliteit",
        HR: "Nacionalnost",
        ES: "Nacionalidad",
        IT: "Nazionalità",
        FR: "Nationalité",
        PL: "Narodowość",
        HU: "Állampolgárság",
        SK: "Národnosť",
        CZ: "Národnost",
    },
    nationalityLabel: {
        DE: "Nationalität",
        EN: "Nationality",
        NL: "Nationaliteit",
        HR: "Nacionalnost",
        ES: "Nacionalidad",
        IT: "Nazionalità",
        FR: "Nationalité",
        PL: "Narodowość",
        HU: "Állampolgárság",
        SK: "Národnosť",
        CZ: "Národnost",
    },
    thanks: {
        DE: "Dankeschön!",
        EN: "Thank you!",
        NL: "Bedankt!",
        HR: "Hvala!",
        ES: "¡Gracias!",
        IT: "Grazie!",
        FR: "Merci !",
        PL: "Dziękujemy!",
        HU: "Köszönjük!",
        SK: "Ďakujeme!",
        CZ: "Děkujeme!",
    },
    returnTablet: {
        DE: "Bitte übergeben Sie das Tablet wieder an die Rezeption.",
        EN: "Please return the tablet to the reception.",
        NL: "Gelieve de tablet terug te geven aan de receptie.",
        HR: "Molimo vratite tablet na recepciju.",
        ES: "Por favor, devuelva la tablet a la recepción.",
        IT: "Si prega di restituire il tablet alla reception.",
        FR: "Veuillez retourner la tablette à la réception.",
        PL: "Proszę zwrócić tablet na recepcję.",
        HU: "Kérjük, adja vissza a tabletet a recepcióra.",
        SK: "Prosím, vráťte tablet na recepciu.",
        CZ: "Prosím, vraťte tablet na recepci.",
    },
    finishBtn: {
        DE: "Von der Rezeption bestätigt",
        EN: "Confirmed by Reception",
        NL: "Bevestigd door receptie",
        HR: "Potvrđeno od recepcije",
        ES: "Confirmado por la recepción",
        IT: "Confermato dalla reception",
        FR: "Confirmé par la réception",
        PL: "Potwierdzone przez recepcję",
        HU: "Recepció által megerősítve",
        SK: "Potvrdené recepciou",
        CZ: "Potvrzeno recepcí",
    },
};

selection.addEventListener("change", () => {
    const lang = selection.value;
    for (let id in languageDict) {
        try {
            document.getElementById(id).innerHTML = languageDict[id][lang];
        } catch {}
    }
});
