const selection = document.getElementById("language");

const languageDict = {
    // secretText: {
    //     DE: "Kennwort eingeben",
    //     EN: "Enter password",
    //     NL: "Wachtwoord invoeren",
    //     HR: "Unesite lozinku",
    //     ES: "Introducir contraseña",
    //     IT: "Inserisci password",
    //     FR: "Entrez le mot de passe",
    //     PL: "Wprowadź hasło",
    //     HU: "Adja meg a jelszót",
    //     SK: "Zadajte heslo"
    // },
    // cancelSecretBtn: {
    //     DE: "Abbrechen",
    //     EN: "Cancel",
    //     NL: "Annuleren",
    //     HR: "Odustani",
    //     ES: "Cancelar",
    //     IT: "Annulla",
    //     FR: "Annuler",
    //     PL: "Anuluj",
    //     HU: "Mégse",
    //     SK: "Zrušiť"
    // },
    // chooseFolderTxt: {
    //     DE: "Es muss ein Ordner zum Speichern der Datei ausgewählt werden!",
    //     EN: "A folder must be selected to save the file!",
    //     NL: "Er moet een map worden geselecteerd om het bestand op te slaan!",
    //     HR: "Morate odabrati mapu za spremanje datoteke!",
    //     ES: "¡Debe seleccionar una carpeta para guardar el archivo!",
    //     IT: "È necessario selezionare una cartella per salvare il file!",
    //     FR: "Un dossier doit être sélectionné pour enregistrer le fichier !",
    //     PL: "Należy wybrać folder do zapisania pliku!",
    //     HU: "Mappát kell kiválasztani a fájl mentéséhez!",
    //     SK: "Je potrebné vybrať priečinok na uloženie súboru!"
    // },
    // chooseFolder: {
    //     DE: "Ordner auswählen",
    //     EN: "Choose Folder",
    //     NL: "Map kiezen",
    //     HR: "Odaberi mapu",
    //     ES: "Seleccionar carpeta",
    //     IT: "Scegli cartella",
    //     FR: "Choisir un dossier",
    //     PL: "Wybierz folder",
    //     HU: "Mappa kiválasztása",
    //     SK: "Vybrať priečinok"
    // },
    roomNumberLabel: {
        DE: "Zimmernummer",
        EN: "Room Number",
        NL: "Kamernummer",
        HR: "Broj sobe",
        ES: "Número de habitación",
        IT: "Numero della stanza",
        FR: "Numéro de chambre",
        PL: "Numer pokoju",
        HU: "Szobaszám",
        SK: "Číslo izby",
    },
    quantityLabel: {
        DE: "Personen",
        EN: "Guests",
        NL: "Personen",
        HR: "Osobe",
        ES: "Personas",
        IT: "Persone",
        FR: "Personnes",
        PL: "Osoby",
        HU: "Vendégek",
        SK: "Osoby",
    },
    startCheckInBtn: {
        DE: "Check-In Starten",
        EN: "Start Check-In",
        NL: "Check-in Starten",
        HR: "Započni prijavu",
        ES: "Iniciar check-in",
        IT: "Avvia check-in",
        FR: "Commencer l'enregistrement",
        PL: "Rozpocznij zameldowanie",
        HU: "Bejelentkezés indítása",
        SK: "Spustiť check-in",
    },
    cancelCheckInBtn: {
        DE: "Check-In Abbrechen",
        EN: "Cancel Check-In",
        NL: "Check-in Annuleren",
        HR: "Otkaži prijavu",
        ES: "Cancelar check-in",
        IT: "Annulla check-in",
        FR: "Annuler l'enregistrement",
        PL: "Anuluj zameldowanie",
        HU: "Bejelentkezés megszakítása",
        SK: "Zrušiť check-in",
    },
    firstnameLabel: {
        DE: "Vorname",
        EN: "First Name",
        NL: "Voornaam",
        HR: "Ime",
        ES: "Nombre",
        IT: "Nome",
        FR: "Prénom",
        PL: "Imię",
        HU: "Keresztnév",
        SK: "Meno",
    },
    lastnameLabel: {
        DE: "Familienname",
        EN: "Last Name",
        NL: "Achternaam",
        HR: "Prezime",
        ES: "Apellido",
        IT: "Cognome",
        FR: "Nom de famille",
        PL: "Nazwisko",
        HU: "Vezetéknév",
        SK: "Priezvisko",
    },
    emailLabel: {
        DE: "E-Mail",
        EN: "Email",
        NL: "E-mail",
        HR: "E-mail",
        ES: "Correo electrónico",
        IT: "E-mail",
        FR: "E-mail",
        PL: "E-mail",
        HU: "E-mail",
        SK: "E-mail",
    },
    countryLabel: {
        DE: "Land",
        EN: "Country",
        NL: "Land",
        HR: "Država",
        ES: "País",
        IT: "Paese",
        FR: "Pays",
        PL: "Kraj",
        HU: "Ország",
        SK: "Krajina",
    },
    cityLabel: {
        DE: "Ort",
        EN: "City",
        NL: "Stad",
        HR: "Grad",
        ES: "Ciudad",
        IT: "Città",
        FR: "Ville",
        PL: "Miasto",
        HU: "Város",
        SK: "Mesto",
    },
    zipcodeLabel: {
        DE: "PLZ",
        EN: "ZIP Code",
        NL: "Postcode",
        HR: "Poštanski broj",
        ES: "Código postal",
        IT: "CAP",
        FR: "Code postal",
        PL: "Kod pocztowy",
        HU: "Irányítószám",
        SK: "PSČ",
    },
    streetLabel: {
        DE: "Straße",
        EN: "Street",
        NL: "Straat",
        HR: "Ulica",
        ES: "Calle",
        IT: "Via",
        FR: "Rue",
        PL: "Ulica",
        HU: "Utca",
        SK: "Ulica",
    },
    housenumberLabel: {
        DE: "Hausnummer",
        EN: "House Number",
        NL: "Huisnummer",
        HR: "Kućni broj",
        ES: "Número",
        IT: "Numero civico",
        FR: "Numéro",
        PL: "Numer domu",
        HU: "Házszám",
        SK: "Súpisné číslo",
    },
    copyAddressLabel: {
        DE: "Adresse für nächste Person kopieren",
        EN: "Copy address for next person",
        NL: "Adres kopiëren voor volgende persoon",
        HR: "Kopiraj adresu za sljedeću osobu",
        ES: "Copiar dirección para la siguiente persona",
        IT: "Copia indirizzo per la prossima persona",
        FR: "Copier l'adresse pour la personne suivante",
        PL: "Skopiuj adres dla następnej osoby",
        HU: "Cím másolása a következő személyhez",
        SK: "Skopírovať adresu pre ďalšiu osobu",
    },
    nextBtn: {
        DE: "Weiter",
        EN: "Next",
        NL: "Volgende",
        HR: "Dalje",
        ES: "Siguiente",
        IT: "Avanti",
        FR: "Suivant",
        PL: "Dalej",
        HU: "Következő",
        SK: "Ďalej",
    },
    tableFirstname: {
        DE: "Vorname",
        EN: "First Name",
        NL: "Voornaam",
        HR: "Ime",
        ES: "Nombre",
        IT: "Nome",
        FR: "Prénom",
        PL: "Imię",
        HU: "Keresztnév",
        SK: "Meno",
    },
    tableLastname: {
        DE: "Nachname",
        EN: "Last Name",
        NL: "Achternaam",
        HR: "Prezime",
        ES: "Apellido",
        IT: "Cognome",
        FR: "Nom de famille",
        PL: "Nazwisko",
        HU: "Vezetéknév",
        SK: "Priezvisko",
    },
    tableEmail: {
        DE: "E-Mail",
        EN: "Email",
        NL: "E-mail",
        HR: "E-mail",
        ES: "Correo electrónico",
        IT: "E-mail",
        FR: "E-mail",
        PL: "E-mail",
        HU: "E-mail",
        SK: "E-mail",
    },
    tableCountry: {
        DE: "Land",
        EN: "Country",
        NL: "Land",
        HR: "Država",
        ES: "País",
        IT: "Paese",
        FR: "Pays",
        PL: "Kraj",
        HU: "Ország",
        SK: "Krajina",
    },
    tableCity: {
        DE: "Ort",
        EN: "City",
        NL: "Stad",
        HR: "Grad",
        ES: "Ciudad",
        IT: "Città",
        FR: "Ville",
        PL: "Miasto",
        HU: "Város",
        SK: "Mesto",
    },
    tableZipcode: {
        DE: "PLZ",
        EN: "ZIP Code",
        NL: "Postcode",
        HR: "Poštanski broj",
        ES: "Código postal",
        IT: "CAP",
        FR: "Code postal",
        PL: "Kod pocztowy",
        HU: "Irányítószám",
        SK: "PSČ",
    },
    tableStreet: {
        DE: "Straße",
        EN: "Street",
        NL: "Straat",
        HR: "Ulica",
        ES: "Calle",
        IT: "Via",
        FR: "Rue",
        PL: "Ulica",
        HU: "Utca",
        SK: "Ulica",
    },
    tableHousenumber: {
        DE: "Nr",
        EN: "No.",
        NL: "Nr.",
        HR: "Br.",
        ES: "Nº",
        IT: "N.",
        FR: "N°",
        PL: "Nr",
        HU: "Sz.",
        SK: "Č.",
    },
    thanks: {
        DE: "Dankeschön!",
        EN: "Thank you!",
        NL: "Bedankt!",
        HR: "Hvala!",
        ES: "¡Gracias!",
        IT: "Grazie!",
        FR: "Merci !",
        PL: "Dziękujemy!",
        HU: "Köszönjük!",
        SK: "Ďakujeme!",
    },
    returnTablet: {
        DE: "Bitte übergeben Sie das Tablet wieder an die Rezeption.",
        EN: "Please return the tablet to the reception.",
        NL: "Gelieve de tablet terug te geven aan de receptie.",
        HR: "Molimo vratite tablet na recepciju.",
        ES: "Por favor, devuelva la tablet a la recepción.",
        IT: "Si prega di restituire il tablet alla reception.",
        FR: "Veuillez retourner la tablette à la réception.",
        PL: "Proszę zwrócić tablet na recepcję.",
        HU: "Kérjük, adja vissza a tabletet a recepcióra.",
        SK: "Prosím, vráťte tablet na recepciu.",
    },
    finishBtn: {
        DE: "Von der Rezeption bestätigt",
        EN: "Confirmed by Reception",
        NL: "Bevestigd door receptie",
        HR: "Potvrđeno od recepcije",
        ES: "Confirmado por la recepción",
        IT: "Confermato dalla reception",
        FR: "Confirmé par la réception",
        PL: "Potwierdzone przez recepcję",
        HU: "Recepció által megerősítve",
        SK: "Potvrdené recepciou",
    },
};

selection.addEventListener("change", () => {
    const lang = selection.value;
    for (let id in languageDict) {
        document.getElementById(id).innerHTML = languageDict[id][lang];
    }
});
